[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "growbuddies"
version = "2023.01.25"
readme = "README.md"
description = "Buddies to help maximize the growth of plants in your indoor garden."
dependencies = [
    "influxdb ~=5.3.1",
    "paho_mqtt ~=1.6.1",
]

[project.urls]
"Homepage" = "https://github.com/solarslurpi/GrowBuddies"

[project.scripts]
store_readings = "growbuddies.store_readings:main"

[tool.black]
line-length = 119

